### ISSUE TITLE
azure_core 0.19.0 fails to build for wasm when using reqwest

### ISSUE THREAD

**Issue by johnbatty** [Azure/azure-sdk-for-rust#1554]
A recent fix https://github.com/Azure/azure-sdk-for-rust/pull/1550 added a call to `reqwest::ClientBuilder::pool_max_idle_per_host()`.  Unfortunately this method does not exist in the reqwest wasm implementation:

```
error[E0599]: no method named `pool_max_idle_per_host` found for struct `ClientBuilder` in the current scope
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/azure_core-0.19.0/src/http_client/reqwest.rs:18:10
   |
17 |       let client = ::reqwest::ClientBuilder::new()
   |  __________________-
18 | |         .pool_max_idle_per_host(0)
   | |         -^^^^^^^^^^^^^^^^^^^^^^ method not found in `ClientBuilder`
   | |_________|
   | 
```

I noticed this when migrating the azure-devops-rust-api to 0.19.0 (the [CI build broke](https://github.com/microsoft/azure-devops-rust-api/actions/runs/7440837772/job/20242278163?pr=321)).  Not sure why the azure-sdk-for-rust CI build didn't fail - I believe it also does a wasm build.  I guess it may not enable the `enable_reqwest` feature?

The fix is obviously to only include the new code for non-wasm builds.
