### ISSUE TITLE
sdk/identity build broken due to oauth2 package update

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-sdk-for-rust#134]
```
error[E0277]: `?` couldn't convert the error to `RequestTokenError<oauth2::reqwest::Error<reqwest::Error>, StandardErrorResponse<BasicErrorResponseType>>`
  --> sdk\identity\src\authorization_code_flow.rs:94:19
```

The package worked with 4.0.0-alpha.2 but not 4.0.0-alpha.3. Should lock to 4.0.0-alpha.2 in code since alpha can have breaking changes

**Comment by rylev** [comment]
This was fixed by #136
