### PR TITLE
Relocate CARGO_HOME to the agent temp volume

### PR DESCRIPTION
**Pull request by danieljurek**
Cargo's registry cache and `cargo install` output live in `$CARGO_HOME` and can reach several GB on the OS volume. Point it at `$(Agent.TempDirectory)/cargo` from `variables/rust.yml` so every Rust pipeline, including release, picks it up.

- `use-rust.yml` prepends `$(CARGO_HOME)/bin` to `PATH` so `taplo` and `cargo2junit` still resolve
- Drops the `DOCKER_TMPDIR` and `TMPDIR` variables proposed in #4198: `DOCKER_TMPDIR` moves only Docker client scratch files, not the daemon image storage that fills the disk, and `TMPDIR` is ignored on Windows

Supersedes #4198.

### CODE REVIEW

**Comment by danieljurek** [comment]
Ran `rust - cosmos` ([6699805](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=6699805)) and `rust - pullrequest` ([6699803](https://dev.azure.com/azure-sdk/public/_build/results?buildId=6699803)) and scanned every log for disk pressure.

| Build | Branch | `Free disk space on / is lower than 5%` warnings |
|---|---|---|
| 6699119 | main | Analyze, vnext emulator test (95.0–96.4% used) |
| 6694858 | main | Analyze, vnext emulator test, Pack Crates (95.0–96.4% used) |
| 6699805 | this PR | none in 696 logs |
| 6699803 | this PR | none in 287 logs |

Verified `CARGO_HOME` is honored end to end — `Wrote cargo config to /mnt/vss/_work/_temp/cargo/config.toml` — and all emulator/test jobs on Linux, Windows, and macOS passed.

`Pack Crates` fails with `unresolved import crate::feed::FeedBody`, which also fails identically on main in 6699119. Unrelated to this change.

**Review by heaths — APPROVED** [review]
Looks good besides Copilot's finding, which sounds entirely plausible.

File: eng/pipelines/templates/steps/use-rust.yml [hunk 1]
```diff
@@ -21,6 +21,18 @@ parameters:
...
+# subcommands there, but tools invoked directly (taplo, cargo2junit) need it on PATH.
+- pwsh: |
+    $cargoBin = ([System.IO.Path]::Combine($env:CARGO_HOME, 'bin'))
+    New-Item -ItemType Directory -Force -Path $cargoBin | Out-Null
+
+    if (($env:PATH -split [System.IO.Path]::PathSeparator) -notcontains $cargoBin) {
+      Write-Host "##vso[task.prependpath]$cargoBin"
+    }
+  displayName: Add CARGO_HOME/bin to PATH
+  condition: and(succeeded(), ne(variables['CARGO_HOME'], ''))
```
[the remark this answers is not in the document]
Comment (danieljurek) [reply eng/pipelines/templates/steps/use-rust.yml:34]: Good catch on the gap — `jobs/perf.yml` did leave perf jobs on the OS volume. Fixed in 850fbe94b0.

I set `CARGO_HOME` directly rather than including `variables/rust.yml`, because that template also carries `RUSTFLAGS: -Dwarnings` and `RUSTDOCFLAGS: -Dwarnings`. Pulling it into perf would newly promote every warning in a perf build to an error, which is a behavior change well beyond the disk fix.

Every other `use-rust.yml` consumer already inherits `variables/rust.yml`: `ci.tests.yml`, `analyze.yml`, and `pack.yml` via the Build stage, `live.tests.yml` via the live test stages, and `archetype-rust-release.yml` via `Release_Batch`. Perf was the only gap.

**Comment by danieljurek** [comment]
Thanks. I'm having Copilot locally figure out if Copilot has a point.

File: eng/pipelines/templates/jobs/perf.yml [hunk 2]
```diff
@@ -33,6 +33,11 @@ extends:
   parameters:
     Variables:
       - template: /eng/pipelines/templates/variables/globals.yml@self
+      # Keep the cargo cache off the OS volume like every other Rust pipeline.
+      # Set directly rather than pulling in `variables/rust.yml`, which would also
+      # apply `RUSTFLAGS: -Dwarnings` to perf builds.
+      - name: CARGO_HOME
+        value: $(Agent.TempDirectory)/cargo
     Language: Rust
```
Comment (heaths) [inline eng/pipelines/templates/jobs/perf.yml]: Why not just add these to `globals.yml`?

**Review by heaths — APPROVED** [review]

File: eng/pipelines/templates/steps/use-rust.yml (hunk 1 above)
[the remark this answers is not in the document]
Comment (danieljurek) [reply eng/pipelines/templates/steps/use-rust.yml:34]: (this last response was written by AI when I asked it to look into the suggestion) 

It's a nice sentiment but perf jobs aren't subject to the same disk space concerns and therefore outside the scope of this change. It'd be nice to have but I don't think we should try to harmonize perf.yml and ci.yml in this PR. 

This is going to be reverted.

File: eng/pipelines/templates/jobs/perf.yml (hunk 2 above)
Comment (danieljurek) [reply eng/pipelines/templates/jobs/perf.yml]: [overwriting unprompted copilot response] 

Let's keep perf outside the scope of this as it's not affected right now. We can add changes later to help with disk space on perf agents if it becomes a problem. 

I think `CARGO_HOME` probably goes in `rust.yml` variables where the other rust-related configs belong. Another possibility would be to make it a "runtime" declared environment variable in `use-rust.yml` but I prefer static and discoverable variables over runtime declared variables where possible.

**Review by heaths — APPROVED** [review]
